# Generated by Django 3.1.2 on 2020-10-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of Squirrel sighting')),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of Squirrel sighting')),
                ('unique_id', models.CharField(help_text='Unique ID of Squirrel', max_length=100)),
                ('shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift of Squirrel', max_length=2)),
                ('date', models.DateField(blank=True, help_text='Date of record')),
                ('age', models.CharField(blank=True, choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult')], help_text='Age of Squirrel', max_length=8)),
                ('fur_color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray')], max_length=20)),
                ('running', models.BooleanField(blank=True)),
                ('eating', models.BooleanField(blank=True)),
                ('climbing', models.BooleanField(blank=True)),
            ],
        ),
    ]
